//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.tm.model;

/**
 * trffcmngr sort attribute.
 */
public enum trffcmngrSortAttribute {

    /** Sorts by name */
    NAME

}
