//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.tm.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.api.Transportable;
import com.hp.sdn.BaseModel;
import com.hp.sdn.auditlog.AuditLogEntry;
import com.hp.sdn.Model;

/**
 * Sample trffcmngr domain model.
 */
public class trffcmngr extends Model<trffcmngr> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public trffcmngr() {
        super();
    }

    /** 
     * Creates a new trffcmngr entity. 
     *
     * @param name trffcmngr name
     */
    public trffcmngr(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new trffcmngr entity. 
     *
     * @param id trffcmngr unique id
     * @param name trffcmngr name
     */
    public trffcmngr(Id<trffcmngr, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the trffcmngr name.
     *
     * @return trffcmngr name
     */
    public String name() {
        return name;
    }

    /**
     * Set the trffcmngr name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
