//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.tm.api;

import java.util.UUID;

import com.fct.tm.model.trffcmngr;
import com.hp.api.NotFoundException;

import com.hp.api.Id;

import java.util.Collection;

/**
 * Sample trffcmngr service interface.
 */
public interface trffcmngrService {

    /**
     * Get all trffcmngr items.
     *
     * @return collection of all trffcmngr items
     */
   // public Collection<trffcmngr> getAll();

    /** 
     * Creates a new trffcmngr entity.
     *
     * @param id unique id to be assigned to the new trffcmngr entity.
     * @param name trffcmngr name
     * @return newly created trffcmngr
     */
   // public trffcmngr create(String name);

    /**
     * Get the trffcmngr with the specified unique id.
     *
     * @param uid unique id of the trffcmngr entity to be retrieved
     * @return trffcmngr with the given unique id
     * @throws NotFoundException if the requested trffcmngr was not found
     */
    //public trffcmngr get(Id<trffcmngr, UUID> id);

    /**
     * Delete the trffcmngr with the specified id.
     *
     * @param uid unique id of the trffcmngr entity to be deleted
     * @return deleted trffcmngr
     * @throws NotFoundException if the requested trffcmngr was not found
     */
   // public void delete(Id<trffcmngr, UUID> id);

}
