//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.tm.impl;

import static org.junit.Assert.*;

import java.util.UUID;

import com.hp.api.NotFoundException;

import com.fct.tm.model.trffcmngr;
import com.fct.tm.api.trffcmngrService;

import com.hp.api.Id;

import org.junit.Before;
import org.junit.Test;

/**
 * Sample test of the trffcmngr service implementation.
 */
public class trffcmngrManagerTest {
  
    /*private trffcmngrService svc;

    @Before
    public void setUp() {
        svc = new trffcmngrManager();
    }
  
    @Test
    public void basics() {
        trffcmngr s = svc.create("Gizmo");
        assertNotNull("incorrect create", s.getId());
        assertEquals("incorrect get", s, svc.get(s.getId()));
        assertEquals("incorrect name", "Gizmo", s.name());
        svc.delete(s.getId());
        try{
            svc.get(s.getId());
            fail("Expected exception");
        } catch(NotFoundException e) {
            
        }
    }

    @Test
    public void defaults() {
        trffcmngr s = svc.create(null);
        assertNotNull("incorrect id", s.getId());
        assertNotNull("incorrect name", s.name());
    }

    @Test(expected=NotFoundException.class)
    public void notFound() {
        Id<trffcmngr, UUID> id = Id.valueOf(UUID.randomUUID());
        svc.get(id);
    }*/
}
