//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.fct.tm.impl;


import org.apache.felix.scr.annotations.Activate;
import org.apache.felix.scr.annotations.Component;
import org.apache.felix.scr.annotations.Deactivate;
import org.apache.felix.scr.annotations.Reference;
import org.apache.felix.scr.annotations.ReferenceCardinality;
import org.apache.felix.scr.annotations.ReferencePolicy;
import org.apache.felix.scr.annotations.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fct.tm.api.trffcmngrService;
import com.fct.tm.listener.PacketListener;
import com.fct.tm.listener.SwitchListener;
import com.hp.of.ctl.ControllerService;

/**
 * Sample trffcmngr service implementation.
 */
@Component(metatype=true)
@Service
public class trffcmngrManager implements trffcmngrService {
	
	@Reference(policy = ReferencePolicy.DYNAMIC, cardinality = ReferenceCardinality.MANDATORY_UNARY)
	private volatile ControllerService controllerService;
	private static final Logger LOG = LoggerFactory.getLogger(trffcmngrManager.class);
	
	private SwitchListener switchListener;
	private PacketListener packetListener;

    
	
	@Activate
	protected void activate(){
		LOG.info("TrafficManager: Activated!!!");
		switchListener = new SwitchListener();
		switchListener.init(controllerService);
		switchListener.startUp();
		
		packetListener = new PacketListener();
		packetListener.init(controllerService);
		packetListener.startUp();
		
	}
	
	@Deactivate
	protected void deactivate(){
		LOG.info("TrafficManager: Deactivated!!!");
		switchListener.shutDown();
		packetListener.shutDown();
		
	}
/*
	@Override
	public Collection<trffcmngr> getAll() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public trffcmngr create(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public trffcmngr get(Id<trffcmngr, UUID> id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void delete(Id<trffcmngr, UUID> id) {
		// TODO Auto-generated method stub
		
	}
	*/

}
